// Code generated by scripts/snapshot-identity.py; DO NOT EDIT.
package v8go

var snapshotNativeIdentity = map[string]string{
	"darwin_amd64":  "2c1fbed73a7557f289b3201f90748dcdfcccf716de3e47457c53e26fb8eccb25",
	"darwin_arm64":  "c766d27febc6c3405280775148fb831fbbed0ce520a06ccef19c43ca6e068726",
	"linux_amd64":   "c232ac252c166c29b0239d921be77035cd91e6838688bc57a177a0b5c46615e0",
	"linux_arm64":   "4861957755f54650afedd906a4a5945bb8347fbddd099d73a194e2518ed7f8fc",
	"windows_amd64": "81a375192e91711979a8563dc68e9fb881bc954f8599fde8be1df836104d6722",
	"windows_arm64": "8968b6cb13e0d463190be13df7e6b7b2aaf59e2bc16f8a801cf270d3b9c70204",
}
