#!/usr/bin/env python3
"""Regenerate snapshot compatibility IDs whenever native archives change."""
from pathlib import Path
import hashlib
import subprocess
import sys
root = Path(__file__).resolve().parent.parent
lines = ['// Code generated by scripts/snapshot-identity.py; DO NOT EDIT.', 'package v8go', '', 'var snapshotNativeIdentity = map[string]string{']
for manifest in sorted((root/'deps').glob('*/libmanifest')):
    digest = hashlib.sha256()
    for name in manifest.read_text().splitlines():
        with (manifest.parent/name).open('rb') as archive:
            while block := archive.read(1024*1024): digest.update(block)
    lines.append(f'"{manifest.parent.name}": "{digest.hexdigest()}",')
lines.append('}')
generated = subprocess.check_output(['gofmt'], input=('\n'.join(lines)+'\n').encode())
output = root/'snapshot_identity.go'
if '--check' in sys.argv:
    if output.read_bytes() != generated:
        sys.exit('snapshot identities are stale; run python3 scripts/snapshot-identity.py')
else:
    output.write_bytes(generated)
